[[thermometers]]
name = "4K"
hardware = "DummyThermometer"
# Arguments that will be passed to setup() in the hardware driver
setup.address = "COM1"

[[thermometers]]
name = "1K"
hardware = "DummyThermometer"
setup.address = "COM2"

[[thermometers]]
name = "1K-main-plate"
hardware = "DummyThermometer"
setup.address = "COM1"

[[thermometers]]
name = "pump"
hardware = "DummyThermometer"
setup.address = "COM4"

[[thermometers]]
name = "heat_switch"
hardware = "DummyThermometer"
setup.address = "COM7"

[[heaters]]
name = "PUMPHEATER"
hardware = "DummyHeater"
setup.address = "COM6"
max_value = 15

[[heaters]]
name = "HS_HEATER"
hardware = "DummyHeater"
setup.address = "COM9"
max_value = 25

